install.packages("dplyr")
library(dplyr) 
mecha_car_table <- read.csv(file='MechaCar_mpg.csv',check.names=F,stringsAsFactors = F)
lm(mpg~vehicle_length+vehicle_weight+spoiler_angle+ground_clearance+AWD,data=mecha_car_table)
summary(lm(mpg~vehicle_length+vehicle_weight+spoiler_angle+ground_clearance+AWD,data=mecha_car_table))
suspension_coil_table<- read.csv(file='Suspension_Coil.csv',check.names=F,stringsAsFactors = F)
total_summary <- suspension_coil_table %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI))
lot_summary <-  suspension_coil_table %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI))
?t.test()
t.test(x=suspension_coil_table$PSI, mu=1500)
pop1 <- subset(suspension_coil_table, Manufacturing_Lot=='Lot1')
t.test(x=pop1$PSI, mu=1500) 
pop2 <- subset(suspension_coil_table, Manufacturing_Lot=='Lot2') 
t.test(x=pop2$PSI, mu=1500) 
pop3 <- subset(suspension_coil_table, Manufacturing_Lot=='Lot3') 
t.test(x=pop3$PSI, mu=1500) 
